### ISSUE TITLE
Way to set language for articles in OJS Export

### ISSUE THREAD

**Issue by EmreDan** [pkp/crossref-ojs#21] opened 2022-12-20 18:12 UTC
Hello, as I have checked from the XML file exported from the plugin, the language is set only per <contributor> tag, not per <journal_article> tag. Is there a way to set the article languages in the settings, so that the CrossRef XML Export Plugin
exports also the language of the article to Crossref, and to their partners through them.

**Comment by fgnievinski** [comment] 2023-01-20 13:36
> the language is set only per tag

you mean, the language is set only per _author_ tag? that's what I've been able to confirm, e.g.:
https://doi.crossref.org/servlet/query?pid=a@b.c&id=10.14393/rbcv74n3-60846&format=info

it's set in `ArticleCrossrefXmlFilter.php`:
https://github.com/pkp/crossref-ojs/blob/main/filter/ArticleCrossrefXmlFilter.php#L162

**Comment by fgnievinski** [comment] 2023-01-20 14:09
> Is there a way to set the article languages in the settings, so that the CrossRef XML Export Plugin exports also the language of the article to Crossref,

an easier solution would be to keep grabbing the metadata only in the submission primary language and implement only support for setting the article's language attribute during the crossref export.

if the editor/admin wants to change the submission primary language, they can always use the quicksubmit plugin (or wait for https://github.com/pkp/pkp-lib/issues/5502).

**Comment by fgnievinski** [comment] 2023-01-30 23:40
I've confirmed the language attribute can be set preferably at both journal-level and article-level, as per CrossRef support forum:, e.g.:
```
<journal>
<journal_metadata language="fr">
<full_title>Revue scientifique</full_title>
</journal_metadata>
<journal_article publication_type="full_text">
<titles language="fr">
<title>Quand vos meilleures métadonnées ne suffisent pas: travailler avec une spécification imparfaite</title>
</titles>
</journal_metadata>
</journal>
```
https://community.crossref.org/t/multi-language-support/3054/12

**Comment by bozana** [comment] 2023-05-26 12:00
Currently the article metadata are exported in the article primary language. Thus, do I understand it correctly, that the goal/requirement here is to export all metadata, in all languages, but to define the article primary language using the `language` attribute in the `journal_article` element? Is only Crossref export topic of this issue?

**Comment by bozana** [comment] 2023-07-04 08:41
@ajnyga, because this issue is assigned to CRAFT OA: is the issue maybe solved with https://github.com/pkp/pkp-lib/issues/9126? And if not, what else would be needed? Thanks a lot!

**Comment by bozana** [comment] 2023-07-05 13:22
@ajnyga, now I saw/read the CRAFT OA document considering this issue. I would suggest to open a new issue for that part of the CRAFT OA package in pkp-lib/issues/ because this issue is only opened for Crossref (repository/plugin) and in the project it seems you will investigate also other services/places in the code.

**Comment by fgnievinski** [comment] 2023-07-10 04:27
> Thus, do I understand it correctly, that the goal/requirement here is to export all metadata, in all languages, but to define the article primary language using the `language` attribute in the `journal_article` element?

dear @bozana originally I had suggested a gradual approach: first to make more explicit in the metadata which single language is being exported; then, later, support exporting metadata containing multiple languages.

but now I believe the present issue is already fully resolved, given the great work at https://github.com/pkp/pkp-lib/issues/9126.

**Closed** 2023-07-14 12:23 UTC
